services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: opengraph-postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - opengraph_postgres_data:/var/lib/postgresql/data
    networks:
      - opengraph-network
    command: postgres -c listen_addresses='*'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G

  # DB Migration Service
  migration:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    container_name: opengraph-migration
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - opengraph-network
    command: ["alembic", "upgrade", "head"]
    restart: "no"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  # Python FastAPI Backend Server
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    container_name: opengraph-server
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      CLIENT_URL: ${CLIENT_URL}
      SERVER_URL: ${SERVER_URL}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: ${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      APP_NAME: ${APP_NAME}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
      GCS_BUCKET_NAME: ${GCS_BUCKET_NAME}
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    networks:
      - opengraph-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G

  # Prometheus
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: opengraph-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - opengraph_prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    depends_on:
      - server
    networks:
      - opengraph-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

  # Grafana
  grafana:
    image: grafana/grafana:10.1.0
    container_name: opengraph-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - opengraph_grafana_data:/var/lib/grafana
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - opengraph-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

  # React Frontend Client
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
      args:
        VITE_SERVER_BASE_URL: ${VITE_SERVER_BASE_URL}
    container_name: opengraph-client
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/explorer.opengraphlabs.xyz:/etc/letsencrypt/live/explorer.opengraphlabs.xyz
      - /etc/letsencrypt/archive/explorer.opengraphlabs.xyz:/etc/letsencrypt/archive/explorer.opengraphlabs.xyz
    depends_on:
      - server
    environment:
      - VITE_SERVER_BASE_URL=${VITE_SERVER_BASE_URL}
    networks:
      - opengraph-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

# Network configuration for better security
networks:
  opengraph-network:
    driver: bridge

# Persistent volumes
volumes:
  opengraph_postgres_data:
  opengraph_prometheus_data:
  opengraph_grafana_data:
  uploads: 