version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    container_name: opengraph-client
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/explorer.opengraphlabs.xyz:/etc/letsencrypt/live/explorer.opengraphlabs.xyz
      - /etc/letsencrypt/archive/explorer.opengraphlabs.xyz:/etc/letsencrypt/archive/explorer.opengraphlabs.xyz
    depends_on:
      - server
    environment:
      - NODE_ENV=production
    env_file:
      - ./client/.env
    networks:
      - opengraph-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M  

  server:
    build:
      context: .
      dockerfile: docker/converter/Dockerfile
    container_name: opengraph-server
    ports:
      - "3000:3000"
    volumes:
      - ./server/uploads:/app/uploads
    env_file:
      - converter/.env
    networks:
      - opengraph-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1.5G 

networks:
  opengraph-network:
    driver: bridge

volumes:
  uploads: 