
### Convert Model .h5 file to HuggingFace3.0 Model
POST {{http-host}}/api/models/convert
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="model"; filename="model.h5"
Content-Type: application/octet-stream

< ./model.h5
------WebKitFormBoundary7MA4YWxkTrZu0gW--