services:
  postgres:
    image: postgres:15
    container_name: opengraph-postgres
    environment:
      POSTGRES_DB: opengraph
      POSTGRES_USER: opengraph_user
      POSTGRES_PASSWORD: opengraph_pw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U opengraph_user -d opengraph"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: opengraph-api
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgres://opengraph_user:opengraph_pw@postgres:5432/opengraph
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: 