services:
  postgres:
    image: postgres:15
    container_name: opengraph-server-postgres
    environment:
      POSTGRES_DB: opengraph
      POSTGRES_USER: opengraph_user
      POSTGRES_PASSWORD: opengraph_pw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U opengraph_user -d opengraph"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: