"""Add reward system: user points, task rewards, user_reward table

Revision ID: 2e0bfe0a5d64
Revises: b1ab270c6610
Create Date: 2025-08-27 20:21:45.691875

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0bfe0a5d64'
down_revision: Union[str, None] = 'b1ab270c6610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_rewards',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reward_type', sa.Enum('IMAGE_APPROVED', 'TASK_COMPLETED', 'BONUS', 'PENALTY', name='rewardtype'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_id', sa.BigInteger(), nullable=True),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_rewards_image_id'), 'user_rewards', ['image_id'], unique=False)
    op.create_index(op.f('ix_user_rewards_task_id'), 'user_rewards', ['task_id'], unique=False)
    op.create_index(op.f('ix_user_rewards_user_id'), 'user_rewards', ['user_id'], unique=False)
    op.add_column('images', sa.Column('submitted_by', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_images_submitted_by'), 'images', ['submitted_by'], unique=False)
    op.create_foreign_key(None, 'images', 'users', ['submitted_by'], ['id'], ondelete='SET NULL')
    op.add_column('tasks', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('reward_points', sa.Integer(), server_default='10', nullable=False))
    op.add_column('tasks', sa.Column('difficulty_level', sa.Integer(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('total_points', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_points')
    op.drop_column('tasks', 'difficulty_level')
    op.drop_column('tasks', 'reward_points')
    op.drop_column('tasks', 'description')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_index(op.f('ix_images_submitted_by'), table_name='images')
    op.drop_column('images', 'submitted_by')
    op.drop_index(op.f('ix_user_rewards_user_id'), table_name='user_rewards')
    op.drop_index(op.f('ix_user_rewards_task_id'), table_name='user_rewards')
    op.drop_index(op.f('ix_user_rewards_image_id'), table_name='user_rewards')
    op.drop_table('user_rewards')
    # ### end Alembic commands ### 