"""Add Task table and update Image model with status and task_id

Revision ID: 9cc4bcc5e819
Revises: ee7518b9df10
Create Date: 2025-08-17 21:07:12.636872

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc4bcc5e819'
down_revision: Union[str, None] = 'ee7518b9df10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first
    imagestatus_enum = sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='imagestatus')
    imagestatus_enum.create(op.get_bind())
    
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('space', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('target_objects', sa.Text(), nullable=True),
    sa.Column('required_count', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('images', sa.Column('status', imagestatus_enum, server_default='PENDING', nullable=False))
    op.add_column('images', sa.Column('task_id', sa.String(), nullable=True))
    op.alter_column('images', 'dataset_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_index(op.f('ix_images_task_id'), 'images', ['task_id'], unique=False)
    op.create_foreign_key(None, 'images', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_index(op.f('ix_images_task_id'), table_name='images')
    op.alter_column('images', 'dataset_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('images', 'task_id')
    op.drop_column('images', 'status')
    op.drop_table('tasks')
    
    # Drop enum type
    imagestatus_enum = sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='imagestatus')
    imagestatus_enum.drop(op.get_bind())
    # ### end Alembic commands ### 