"""Add user annotation selections table

Revision ID: bbe698169c21
Revises: 4d8c7f7aa563
Create Date: 2025-07-22 12:51:19.231213

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe698169c21'
down_revision: Union[str, None] = '4d8c7f7aa563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_annotation_selections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('selected_annotation_ids_key', sa.String(length=500), nullable=False, comment="Comma-separated sorted annotation IDs (e.g., '1,3,4')"),
    sa.Column('status', sa.String(length=20), nullable=False, comment='PENDING, APPROVED, REJECTED'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_image_selections', 'user_annotation_selections', ['image_id', 'status'], unique=False)
    op.create_index('idx_pending_selections', 'user_annotation_selections', ['status', 'created_at'], unique=False)
    op.create_index('idx_selection_lookup', 'user_annotation_selections', ['image_id', 'selected_annotation_ids_key', 'category_id'], unique=False)
    op.create_index('idx_user_selections', 'user_annotation_selections', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_selections', table_name='user_annotation_selections')
    op.drop_index('idx_selection_lookup', table_name='user_annotation_selections')
    op.drop_index('idx_pending_selections', table_name='user_annotation_selections')
    op.drop_index('idx_image_selections', table_name='user_annotation_selections')
    op.drop_table('user_annotation_selections')
    # ### end Alembic commands ### 