"""Add zkLogin fields to User model

Revision ID: ee7518b9df10
Revises: c43f60ea5976
Create Date: 2025-07-29 14:24:54.950383

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7518b9df10'
down_revision: Union[str, None] = 'c43f60ea5976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('zklogin_salt', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_sub', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_column('users', 'google_sub')
    op.drop_column('users', 'zklogin_salt')
    # ### end Alembic commands ### 